language: python

python:
    - "3.6"
    - "3.7"

before_install:
    - pip --no-cache install -U pip setuptools

install:
    - pip install ".[tests]"

script:
    - python -m unittest discover -s tests
